#debug: true
spring:
  web:
    error:
      include-stacktrace: always #只要报错，就把完整的 Java 异常堆栈信息返回给调用方( dev推荐）
  data:
    redis:
      host: localhost
      port: 6379

mybatis-flex:
  datasource:
    ds1:
      url: jdbc:postgresql://192.168.11.104:5433/flexboot4
      username: flexboot4
      password: flexboot4
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  inject-sql-session-on-mapper-scan: true
  global-config:
    print-banner: false
