-- ============================================================
-- FlexBoot4 Admin Starter menu and permission seed data.
-- Menu/button records are owned by the admin module.
-- ============================================================

INSERT INTO sys_menu (id, parent_id, path, name, component, redirect, title, icon, order_no,
                      hide_in_menu, keep_alive, type, status,
                      create_time, last_modify_time, del_flag, version)
VALUES
('sys_menu_system', NULL, '/system', 'System', 'BasicLayout', '/system/user',
 '系统管理', 'ant-design:setting-outlined', 10, FALSE, FALSE, 'catalog', 1,
 now(), now(), 0, 0),
('sys_menu_devops', NULL, '/devops', 'Devops', 'BasicLayout', '/devops/log',
 '运维管理', 'ant-design:dashboard-outlined', 80, FALSE, FALSE, 'catalog', 1,
 now(), now(), 0, 0)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    path = EXCLUDED.path,
    name = EXCLUDED.name,
    component = EXCLUDED.component,
    redirect = EXCLUDED.redirect,
    title = EXCLUDED.title,
    icon = EXCLUDED.icon,
    order_no = EXCLUDED.order_no,
    hide_in_menu = EXCLUDED.hide_in_menu,
    keep_alive = EXCLUDED.keep_alive,
    type = EXCLUDED.type,
    status = EXCLUDED.status,
    last_modify_time = now();

INSERT INTO sys_menu (id, parent_id, path, name, component, title, icon, order_no,
                      hide_in_menu, keep_alive, type, auth_code, status,
                      create_time, last_modify_time, del_flag, version)
VALUES
('sys_menu_user', 'sys_menu_system', '/system/user', 'SystemUser', '/system/user/list',
 '用户管理', 'ant-design:user-outlined', 1, FALSE, TRUE, 'menu', 'sys:user:list', 1,
 now(), now(), 0, 0),
('sys_menu_role', 'sys_menu_system', '/system/role', 'SystemRole', '/system/role/list',
 '角色管理', 'ant-design:team-outlined', 2, FALSE, TRUE, 'menu', 'sys:role:list', 1,
 now(), now(), 0, 0),
('sys_menu_menu', 'sys_menu_system', '/system/menu', 'SystemMenu', '/system/menu/list',
 '菜单管理', 'ant-design:menu-outlined', 3, FALSE, TRUE, 'menu', 'sys:menu:list', 1,
 now(), now(), 0, 0),
('sys_menu_dept', 'sys_menu_system', '/system/dept', 'SystemDept', '/system/dept/list',
 '部门管理', 'ant-design:apartment-outlined', 4, FALSE, TRUE, 'menu', 'sys:dept:list', 1,
 now(), now(), 0, 0),
('sys_menu_file', 'sys_menu_system', '/system/file', 'SystemFile', '/system/file/index',
 '文件管理', 'ant-design:file-outlined', 5, FALSE, TRUE, 'menu', 'sys:file:list', 1,
 now(), now(), 0, 0),
('sys_menu_config', 'sys_menu_system', '/system/config', 'SystemConfig', '/system/config/index',
 '参数配置', 'ant-design:control-outlined', 6, FALSE, TRUE, 'menu', 'sys:config:list', 1,
 now(), now(), 0, 0),
('sys_menu_dict_type', 'sys_menu_system', '/system/dict-type', 'SystemDictType', '/system/dict-type/index',
 '字典类型', 'ant-design:unordered-list-outlined', 7, FALSE, TRUE, 'menu', 'sys:dict:type:list', 1,
 now(), now(), 0, 0),
('sys_menu_dict_item', 'sys_menu_system', '/system/dict-item', 'SystemDictItem', '/system/dict-item/index',
 '字典项', 'ant-design:bars-outlined', 8, FALSE, TRUE, 'menu', 'sys:dict:item:list', 1,
 now(), now(), 0, 0),
('sys_menu_api_key', 'sys_menu_devops', '/devops/api-key', 'DevopsApiKey', '/devops/api-key/index',
 'API Key', 'ant-design:key-outlined', 1, FALSE, TRUE, 'menu', 'ai:api:key:list', 1,
 now(), now(), 0, 0),
('sys_menu_oper_log', 'sys_menu_devops', '/devops/log', 'DevopsLog', '/devops/log/index',
 '操作日志', 'ant-design:profile-outlined', 2, FALSE, TRUE, 'menu', 'sys:oper:log:list', 1,
 now(), now(), 0, 0),
('sys_menu_monitor', 'sys_menu_devops', '/devops/monitor', 'DevopsMonitor', '/devops/monitor/index',
 '系统监控', 'ant-design:monitor-outlined', 3, FALSE, TRUE, 'menu', 'sys:monitor:stats', 1,
 now(), now(), 0, 0),
('sys_menu_version_log', 'sys_menu_devops', '/devops/version-log', 'DevopsVersionLog', '/devops/version-log/index',
 '版本日志', 'ant-design:history-outlined', 4, FALSE, TRUE, 'menu', 'sys:version:log:list', 1,
 now(), now(), 0, 0)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    path = EXCLUDED.path,
    name = EXCLUDED.name,
    component = EXCLUDED.component,
    title = EXCLUDED.title,
    icon = EXCLUDED.icon,
    order_no = EXCLUDED.order_no,
    hide_in_menu = EXCLUDED.hide_in_menu,
    keep_alive = EXCLUDED.keep_alive,
    type = EXCLUDED.type,
    auth_code = EXCLUDED.auth_code,
    status = EXCLUDED.status,
    last_modify_time = now();

INSERT INTO sys_menu (id, parent_id, path, name, component, title, icon, order_no,
                      hide_in_menu, keep_alive, type, auth_code, status,
                      create_time, last_modify_time, del_flag, version)
VALUES
('sys_user_add_btn', 'sys_menu_user', '', 'SystemUserAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:user:add', 1, now(), now(), 0, 0),
('sys_user_edit_btn', 'sys_menu_user', '', 'SystemUserEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:user:edit', 1, now(), now(), 0, 0),
('sys_user_delete_btn', 'sys_menu_user', '', 'SystemUserDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:user:delete', 1, now(), now(), 0, 0),
('sys_user_export_btn', 'sys_menu_user', '', 'SystemUserExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:user:export', 1, now(), now(), 0, 0),
('sys_user_import_btn', 'sys_menu_user', '', 'SystemUserImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:user:import', 1, now(), now(), 0, 0),
('system_user_reset_password_btn', 'sys_menu_user', '', 'SystemUserResetPassword', '', 'common.resetPassword', '', 91, TRUE, FALSE, 'button', 'sys:user:reset-password', 1, now(), now(), 0, 0),
('sys_role_add_btn', 'sys_menu_role', '', 'SystemRoleAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:role:add', 1, now(), now(), 0, 0),
('sys_role_edit_btn', 'sys_menu_role', '', 'SystemRoleEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:role:edit', 1, now(), now(), 0, 0),
('sys_role_delete_btn', 'sys_menu_role', '', 'SystemRoleDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:role:delete', 1, now(), now(), 0, 0),
('sys_role_export_btn', 'sys_menu_role', '', 'SystemRoleExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:role:export', 1, now(), now(), 0, 0),
('sys_role_import_btn', 'sys_menu_role', '', 'SystemRoleImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:role:import', 1, now(), now(), 0, 0),
('sys_menu_add_btn', 'sys_menu_menu', '', 'SystemMenuAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:menu:add', 1, now(), now(), 0, 0),
('sys_menu_edit_btn', 'sys_menu_menu', '', 'SystemMenuEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:menu:edit', 1, now(), now(), 0, 0),
('sys_menu_delete_btn', 'sys_menu_menu', '', 'SystemMenuDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:menu:delete', 1, now(), now(), 0, 0),
('sys_menu_export_btn', 'sys_menu_menu', '', 'SystemMenuExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:menu:export', 1, now(), now(), 0, 0),
('sys_menu_import_btn', 'sys_menu_menu', '', 'SystemMenuImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:menu:import', 1, now(), now(), 0, 0),
('sys_dept_add_btn', 'sys_menu_dept', '', 'SystemDeptAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:dept:add', 1, now(), now(), 0, 0),
('sys_dept_edit_btn', 'sys_menu_dept', '', 'SystemDeptEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:dept:edit', 1, now(), now(), 0, 0),
('sys_dept_delete_btn', 'sys_menu_dept', '', 'SystemDeptDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:dept:delete', 1, now(), now(), 0, 0),
('sys_dept_export_btn', 'sys_menu_dept', '', 'SystemDeptExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:dept:export', 1, now(), now(), 0, 0),
('sys_dept_import_btn', 'sys_menu_dept', '', 'SystemDeptImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:dept:import', 1, now(), now(), 0, 0),
('sys_file_add_btn', 'sys_menu_file', '', 'SystemFileAdd', '', 'common.add', '', 5, TRUE, FALSE, 'button', 'sys:file:add', 1, now(), now(), 0, 0),
('sys_file_edit_btn', 'sys_menu_file', '', 'SystemFileEdit', '', 'common.edit', '', 6, TRUE, FALSE, 'button', 'sys:file:edit', 1, now(), now(), 0, 0),
('sys_file_upload_btn', 'sys_menu_file', '', 'SystemFileUpload', '', '文件上传', '', 10, TRUE, FALSE, 'button', 'sys:file:upload', 1, now(), now(), 0, 0),
('sys_file_download_btn', 'sys_menu_file', '', 'SystemFileDownload', '', '文件下载', '', 20, TRUE, FALSE, 'button', 'sys:file:download', 1, now(), now(), 0, 0),
('sys_file_delete_btn', 'sys_menu_file', '', 'SystemFileDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:file:delete', 1, now(), now(), 0, 0),
('sys_file_export_btn', 'sys_menu_file', '', 'SystemFileExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:file:export', 1, now(), now(), 0, 0),
('sys_file_import_btn', 'sys_menu_file', '', 'SystemFileImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:file:import', 1, now(), now(), 0, 0),
('sys_config_add_btn', 'sys_menu_config', '', 'SystemConfigAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:config:add', 1, now(), now(), 0, 0),
('sys_config_edit_btn', 'sys_menu_config', '', 'SystemConfigEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:config:edit', 1, now(), now(), 0, 0),
('sys_config_delete_btn', 'sys_menu_config', '', 'SystemConfigDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:config:delete', 1, now(), now(), 0, 0),
('sys_config_export_btn', 'sys_menu_config', '', 'SystemConfigExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:config:export', 1, now(), now(), 0, 0),
('sys_config_import_btn', 'sys_menu_config', '', 'SystemConfigImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:config:import', 1, now(), now(), 0, 0),
('sys_dict_type_add_btn', 'sys_menu_dict_type', '', 'SystemDictTypeAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:dict:type:add', 1, now(), now(), 0, 0),
('sys_dict_type_edit_btn', 'sys_menu_dict_type', '', 'SystemDictTypeEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:dict:type:edit', 1, now(), now(), 0, 0),
('sys_dict_type_delete_btn', 'sys_menu_dict_type', '', 'SystemDictTypeDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:dict:type:delete', 1, now(), now(), 0, 0),
('sys_dict_type_export_btn', 'sys_menu_dict_type', '', 'SystemDictTypeExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:dict:type:export', 1, now(), now(), 0, 0),
('sys_dict_type_import_btn', 'sys_menu_dict_type', '', 'SystemDictTypeImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:dict:type:import', 1, now(), now(), 0, 0),
('sys_dict_item_add_btn', 'sys_menu_dict_item', '', 'SystemDictItemAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:dict:item:add', 1, now(), now(), 0, 0),
('sys_dict_item_edit_btn', 'sys_menu_dict_item', '', 'SystemDictItemEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:dict:item:edit', 1, now(), now(), 0, 0),
('sys_dict_item_delete_btn', 'sys_menu_dict_item', '', 'SystemDictItemDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:dict:item:delete', 1, now(), now(), 0, 0),
('sys_dict_item_export_btn', 'sys_menu_dict_item', '', 'SystemDictItemExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:dict:item:export', 1, now(), now(), 0, 0),
('sys_dict_item_import_btn', 'sys_menu_dict_item', '', 'SystemDictItemImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:dict:item:import', 1, now(), now(), 0, 0),
('ai_api_key_add_btn', 'sys_menu_api_key', '', 'AiApiKeyAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'ai:api:key:add', 1, now(), now(), 0, 0),
('ai_api_key_edit_btn', 'sys_menu_api_key', '', 'AiApiKeyEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'ai:api:key:edit', 1, now(), now(), 0, 0),
('ai_api_key_delete_btn', 'sys_menu_api_key', '', 'AiApiKeyDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'ai:api:key:delete', 1, now(), now(), 0, 0),
('ai_api_key_export_btn', 'sys_menu_api_key', '', 'AiApiKeyExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'ai:api:key:export', 1, now(), now(), 0, 0),
('ai_api_key_import_btn', 'sys_menu_api_key', '', 'AiApiKeyImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'ai:api:key:import', 1, now(), now(), 0, 0),
('sys_version_log_add_btn', 'sys_menu_version_log', '', 'SystemVersionLogAdd', '', 'common.add', '', 10, TRUE, FALSE, 'button', 'sys:version:log:add', 1, now(), now(), 0, 0),
('sys_version_log_edit_btn', 'sys_menu_version_log', '', 'SystemVersionLogEdit', '', 'common.edit', '', 20, TRUE, FALSE, 'button', 'sys:version:log:edit', 1, now(), now(), 0, 0),
('sys_version_log_delete_btn', 'sys_menu_version_log', '', 'SystemVersionLogDelete', '', 'common.delete', '', 30, TRUE, FALSE, 'button', 'sys:version:log:delete', 1, now(), now(), 0, 0),
('sys_version_log_export_btn', 'sys_menu_version_log', '', 'SystemVersionLogExport', '', 'common.export', '', 40, TRUE, FALSE, 'button', 'sys:version:log:export', 1, now(), now(), 0, 0),
('sys_version_log_import_btn', 'sys_menu_version_log', '', 'SystemVersionLogImport', '', 'common.import', '', 50, TRUE, FALSE, 'button', 'sys:version:log:import', 1, now(), now(), 0, 0)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    path = '',
    name = EXCLUDED.name,
    component = '',
    title = EXCLUDED.title,
    icon = EXCLUDED.icon,
    order_no = EXCLUDED.order_no,
    hide_in_menu = TRUE,
    keep_alive = FALSE,
    type = 'button',
    auth_code = EXCLUDED.auth_code,
    status = EXCLUDED.status,
    last_modify_time = now();

INSERT INTO sys_role_menu (id, role_id, menu_id, create_time, last_modify_time, del_flag, version)
SELECT 'sys_role_admin_menu_' || m.id, '2', m.id, now(), now(), 0, 0
FROM sys_menu m
WHERE m.id LIKE 'sys_%'
   OR m.id = 'system_user_reset_password_btn'
   OR m.id LIKE 'ai_api_key_%'
ON CONFLICT (id) DO NOTHING;
